services:
  - type: web
    name: financial-frontend
    env: static
    buildCommand: npm run build
    startCommand: npx serve -s build -l $PORT
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
      - type: rewrite
        source: /*
        destination: /index.html 